### PR TITLE
Allow Lightsaber and Knowledge: Warfare for all systems

### LINKED ISSUE #95: Consider making Lightsaber and Knowledge: Warfare available to all three systems
Dawn of Rebellion opened those two skills to all three systems, and there are many games with mixed systems involved.

Please consider making those skills available to all game system options.

### PR DESCRIPTION
**Pull request by duffn**
Allow `Lightsaber` and `Knowledge: Warfare` for all systems.

Closes #95.

### CODE REVIEW

**Comment by sparkertime** [comment]
Thanks @duffn ! I've been open to PRs for over four years and this is the first time I've actually got one from someone new to the project! How kind!

Any chance you'd also be willing to get rid of the supporting code around the skill -> system mapping? This would be code in `priv/static/js/character.js` as well as the models `web/models/base_skill.ex` and `web/models/character_skill.ex` (and their supporting tests & views)

**Comment by duffn** [comment]
I'll give it a go!

**Comment by duffn** [comment]
Okay, I think that's it. (?)

**Comment by sparkertime** [comment]
I made a couple of minor tweaks but otherwise this looks great

* `character_skill.ex` still referred to system
* kept the column so that we can roll back the deploy if something goes wrong. Once this code is live on production, I'll revert that and drop the column.

Thanks for another great PR!

**Pull request merged**
