### PR TITLE
Restyling

### LINKED ISSUE #111: Styling update
Any interest in a minor styling update? Nothing too involved, but maybe just a Bootswatch style for a little refresh? I played around a bit with Flatly last night: https://github.com/swsheets/swsheets/compare/master...duffn:duffn/flatly-restyle?expand=1

Screen Shot 2019-12-13 at 6 47 08 AM

Screen Shot 2019-12-13 at 6 47 55 AM

Screen Shot 2019-12-13 at 6 48 04 AM

## TODO

- [x] Threshold inputs on character wound and strain are too small.
- [x] Get range and skill in character attacks aligned properly (Firefox).
- [x] Critical in vehicle weapons is misaligned (Chrome) and critical and range (Firefox).
- [x] Vehicle attachment name alignment.

### PR DESCRIPTION
**Pull request by duffn**
This is the restyling mentioned in #111. 

- The CSS is the Flatly Bootswatch style: https://bootswatch.com/3/flatly/
- The main purpose was a styling refresh and that's what many of the changes are surrounding; for example, making the logo taller to fit the header height or setting the border color of the system select on the character page to match the Flatly colors.

The biggest changes outside of those minor tweaks, and where I took the most liberties, are:

- Aligning the vehicle and character edit forms for attacks and attachments. These were easiest to align with labels and full widths for all of the inputs.

Screen Shot 2019-12-15 at 7 44 48 PM

- Setting the width of the character and vehicle lists to 6 columns.

Screen Shot 2019-12-15 at 7 45 30 PM

## TODO

- [x] Padding on the notes sections of the show form for characters is now suddenly broken.
- [x] Numbers in wounds and strain disappear on medium size screens for characters. https://github.com/swsheets/swsheets/pull/118#issuecomment-568500009
- [x] Numbers in wounds and strain disappear on mobile size screens (this happens on current master as well).

Closes #111.

### CODE REVIEW

**Comment by sparkertime** [comment]
While I admit this is a little low contrast for me, I don't object to a fresh coat of paint on the site. A few nitpick-ish things:

Gap between picklist button and border
Screen Shot 2019-12-21 at 4 13 00 PM

Uneven height for Soak relative to other stats
Screen Shot 2019-12-21 at 4 13 08 PM

I think the thick border between Threshold and Current looks a little odd (I care less whether this one gets fixed - I cannot say the current implementation is a masterpiece of design)
Screen Shot 2019-12-21 at 4 13 05 PM

Visual artifacts from what I suspect is upscaling the logo at `priv/static/images/logo.png` instead of downscaling `assets/logo_large.png`
Screen Shot 2019-12-21 at 4 20 47 PM

**Comment by duffn** [comment]
I'll take a look at those changes.

I'm also certainly amenable to trying a different template from Bootswatch: https://bootswatch.com/3/. I suppose I'd even try to tackle upgrading to Bootstrap 4 if that's a route we'd like to take: https://bootswatch.com/.

Though that's going to be about the limit of my "design" skills. 🙂

**Comment by duffn** [comment]
I've made updates on:

- The system dropdown button
- Resizing the image (I'm quite certain I scaled down the larger image the first time around, but have tried again)
- Soak panel padding
Also:
- Added the ellipsis overflow for my creations to mimic the home page
- Fixed padding on mobile sizes on the character and vehicle pages

I'm not quite sure how to solve the border between threshold and current at the moment, so will leave it alone if it's not a blocker.

**Comment by sparkertime** [comment]
Looking great. One last issue I can see - as you resize the width of the character edit screen, you start to lose the numbers in the strain / wounds / defense.

Screen Shot 2019-12-23 at 9 05 07 AM

This happens at what I believe is bootstrap's medium (the smallest size at which the form shows all of soak / strain / wounds / defense in a single line.

**Comment by duffn** [comment]
Ah, darn. I'll take a look but it won't be until after Christmas.

On Dec 23, 2019 8:10 AM, Scott Parker <notifications@github.com> wrote:

Looking great. One last issue I can see - as you resize the width of the character edit screen, you start to lose the numbers in the strain / wounds / defense.

[Screen Shot 2019-12-23 at 9 05 07 AM]<https://user-images.githubusercontent.com/128267/71365227-f58efc00-2563-11ea-816c-75f9ff0560c3.png>

This happens at what I believe is bootstrap's medium (the smallest size at which the form shows all of soak / strain / wounds / defense in a single line.

**Comment by duffn** [comment]
1) I have the threshold and current inputs looking like this now at desktop, <962 >768 and <768 respectively.

Screen Shot 2019-12-28 at 11 56 41 AM

Screen Shot 2019-12-28 at 11 56 51 AM

Screen Shot 2019-12-28 at 11 56 59 AM

2) I'm a bit unclear as to how I'm now (unrelatedly) getting the bottom text boxes _outside_ of the container, causing this issue.

Screen Shot 2019-12-28 at 12 00 05 PM

**Comment by duffn** [comment]
> I'm a bit unclear as to how I'm now (unrelatedly) getting the bottom text boxes outside of the container, causing this issue.

Okay, I discovered that this is due to excessively long characteristics of a character like below. If this section is too large, it breaks the bottom background/obligation/etc. section of the character.

Screen Shot 2019-12-28 at 9 08 58 PM

**Comment by duffn** [comment]
Now I can't recreate this at all. It only seems to be with the single character entry noted above, so I'm not sure what happened. I've tried with a number of different variations and can't do it again.

I think this PR looks good now.

**Comment by sparkertime** [comment]
This is looking really good, but I'm still seeing this issue on medium in Chrome

Screen Shot 2019-12-23 at 9 05 07 AM

Your call on if/how you want to solve before merging. A simple fix is just changing the four `col-sm-3` to be `col-lg-3` which forces medium to use the same layout as smaller sizes. It's not the most beautiful thing at medium, but it works.

**Comment by duffn** [comment]
This is why I’m a backend developer. I’ll play around with it a bit more and then make your suggested update, but likely not for tomorrow morning.

**Pull request merged**
