### PR TITLE
Added un-persisted incrementer/decrementer buttons…

### PR DESCRIPTION
**Pull request by chrisjpowers**
…for changing current wounds and strain numbers without using the edit function. If you decide you like the functionality, then we can get AJAXy and update the server when the buttons are clicked.

screen shot 2015-06-18 at 9 14 11 pm

### CODE REVIEW

**Comment by sparkertime** [comment]
So! This is very interesting and wades directly into the great quandary of SWSheets. The site is solid for character creation and viewing, but it is mediocre for _play_. I see two ways out of this and I have been stuck at this particular fork in the road for some time. Since you are also clearly thinking about this problem, I would love your input @chrisjpowers.

The first option is exactly what you propose - some in-page functionality for editing the parts of a character that are most likely to change during play. That's clearly Wounds and Strain like you proposed, but there's a second tier of stuff like credits, gear, encumbrance, and XP increases. This second tier are conceptually harder to present clean in-page editing interfaces like what you built.

The other option is a hybrid show/edit page similar to what Trello does. In Trello when you are viewing a story and have permission to edit it, you can click on virtually any part of the story card to change _just that part of the form_ into an editor for that field. That has the advantage of providing a clean "read" interface that able to turn into a "write" interface as needed, but the downside is that it is not obvious _at all_ in my opinion. It also complicates some other minor use cases (copy/paste from a Trello card is pretty annoying as your first click to select text will turn the field into an edit box).

Now that I'm writing this however, I'm inclined to kick this decision a bit further down the road and just accept your PR (once the AJAX functionality is in, of course) to see if players actually make use of it. We will need a framework for making AJAX edits to characters anyway (I want the GM interface in #13 to be able to make AJAX requests to grant XP, credits, etc directly to players) so I don't think this will be wasted work.

Unless you know Elixir/Phoenix or are inclined to learn it, I'm happy to build out that AJAX endpoint this weekend. As long as you wrap the HTML inputs in the same `<%= if @viewed_by_owner do %>` check for ownership, the rest should be just a matter of Javascript.

**Comment by sparkertime** [comment]
Also, thanks a ton for this PR and welcome to the Jedi Council =) http://swsheets.com/thanks

**Comment by chrisjpowers** [comment]
I've used SWsheets in one play session so far, and certainly found the wounds/strain to be the primary thing that needed incremental changes. I didn't find it annoying to change my inventory using the regular edit page, but the specific flux of wounds/strain prompted this PR.

I am inclined to learn Elixir, but it won't be this weekend ;) If you have the time to whip up an API endpoint, go for it.

**Comment by sparkertime** [comment]
Just a note to let you know I haven't forgotten about this. In building this over the weekend I realized my current test setup made JSON endpoints untestable. This led to a significant bout of yak shaving to refactor all of my controller tests in https://github.com/citizenparker/swsheets/commit/394ea7282d03fbe129c0da62a841b908361ba3d0. With that finished I can actually start on the backing endpoint now.

**Comment by bknowles** [comment]
Cool!

**Comment by sparkertime** [comment]
@chrisjpowers This feature is _finally_ added and deployed thanks to getting a resolution to some of my testing issues on the Phoenix mailing ist. I don't have great docs for it at the moment but see https://github.com/citizenparker/swsheets/blob/c25788103e0e7b0f59aefbc2fb7bd2b40542467e/test/controllers/api/character_controller_test.exs for usage examples. I know you aren't an Elixirist but the URL and formats of inputs/outputs should be somewhat straightforward. If not let me know and I'll properly document this.

If you have any feedback on that API I'm all ears.

Thanks!

**Comment by chrisjpowers** [comment]
Hey, remember this thing we were talking about back in June? I actually sat down for a few minutes and made it work! Not sure you want to merge it in yet, as it could use some integration tests and a better approach than sending a request on every button push. But it's a start!

**Comment by sparkertime** [comment]
I haven't written a single integration test against the JS in swsheets, and I'm not inclined to start. =)

One minor nitpick - with one exception I've named the HTML element ids with `camelCase` and reserved `hyphenated-words` for CSS classes. Can you change those in your commits?

As for a better approach, I'm not sure I can think of one that is worth it. If you have a better idea, feel free to suggest it. Otherwise I'll merge this PR once the IDs are sorted out. Thanks so much!

**Comment by sparkertime** [comment]
Ooh, wait, sorry, one problem - these will show up for anyone, not just the owner. You need to wrap the code that displays these in the HTML template with the following:

``` elixir
<%= if @viewed_by_owner do %>
...
<% end %>
```

See the top of `web/templates/character/show.html.eex` for an example.

**Comment by chrisjpowers** [comment]
Cool, those changes are made.

**Comment by sparkertime** [comment]
Just kicked the tires on this, it looks beautiful. Thanks for the hard work!

**Pull request merged**
