### PR TITLE
Favorite lists

### PR DESCRIPTION
**Pull request by chrisjpowers**
@citizenparker This is a big enough feature that I want some feedback on it! Both product and code criticism/guidance are welcome.

Be sure to look at the My Lists page before adding a list, so you can see the "no lists" getting started text.

### CODE REVIEW

**Comment by chrisjpowers** [comment]
This would solve #32, btw.

**Comment by sparkertime** [comment]
I like where this is going - seems like the right direction. Some random unsorted thoughts:
- I think lists should be public information. As an character author, I'm interested in knowing what lists my character is a part of. My secret hope is that eventually catalogues of NPCs will be available to GMs via this feature. This is mostly selfish so that I can stop making printable character sheets for the stock NPCs in the core rulebooks.
- I am torn on calling this "list." This is a somewhat dry term for it versus calling it "favorites." On the other hand, I'm realizing this feature could power #13 as well. I think it makes more sense for me to add my players to a special form of a "list" than to a special form of "favorites"
- I like selecting the list at the time of addition.

Some things I think would be great in future work before this is merged in:
- Currently no way to delete a list or remove an item from a list
- Adding paging to lists (my gut instinct is to implement this by having the "My Lists" page be the index of all lists, and then have a "show all" or "show full" button for each that breaks out into a dedicated view. The index just shows the latest X for each list, the show full gives you the full, paginated view.
- Some kind of feedback when you add a character/vehicle a list that something changed. There's no visual feedback. I think DeviantArt's system for managing this is superb. Screenshot:



This button turns a bright color when the item is part of your favorites already, and expanding the list when that's the case gives a visual indication of which lists it is in. Selecting a list it's already in removes it.

Further down the road, I'd love to see all lists an item is part of, but that can wait since this PR is big enough already.

**Comment by sparkertime** [comment]
Oh and I agree this solves for starring. I'll close that issue.

**Comment by sparkertime** [comment]
FYI - I'm going to close this soon unless you want to finish it up and merge it.

**Comment by chrisjpowers** [comment]
Sorry, I'm not going to be able to work on this. Closing.

**Pull request closed without merging**
