### PR TITLE
Make the cancel button go back to the resource

### PR DESCRIPTION
**Pull request by duffn**
Instead of returning to the root route or the character page, make the cancel button go back to the relevant resource.

### CODE REVIEW

**Comment by sparkertime** [comment]
Sadly, this busts against latest master when you try to create a new character. The error message

```
Server: localhost:4000 (http)
Request: GET /c/new
** (exit) an exception was raised:
    ** (ArgumentError) cannot convert nil to param
        (phoenix) lib/phoenix/param.ex:67: Phoenix.Param.Atom.to_param/1
        (edge_builder) EdgeBuilder.Router.Helpers.character_path/4
        (edge_builder) web/templates/character/_form.html.eex:3: EdgeBuilder.CharacterView."_form.html"/1
        (edge_builder) web/templates/character/new.html.eex:4: EdgeBuilder.CharacterView."new.html"/1
        (edge_builder) web/templates/layout/app.html.eex:84: EdgeBuilder.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
```

**Review by sparkertime — CHANGES_REQUESTED** [review]
Happy to merge once the character/new route works

**Comment by duffn** [comment]
Oh shoot, I'll check that out now that the big upgrade PR was merged in.

**Comment by duffn** [comment]
I've updated so it does not crash on new resources and added checks in the tests.

**Pull request merged**
